<section id="pageShow" class="clearfix" style="padding: 10px;">
	 
	
	<h2>Fancy <small><a target="_blank" href="http://fancybox.net" title="Fancy | Documentation">Documentation</a></small></h2>
	<a class="fancy" href="<?php bloginfo('template_url'); ?>/assets/images/default/404.png">Clique aqui para ver o Fancy</a>
	
	<hr />
	
	<h2>Bootstrap Alerts <small><a target="_blank" href="http://twitter.github.com/bootstrap/components.html#alerts" title="Bootstrap Alerts | Documentation">Documentation</a></small></h2>	
    <div class="alert alert-block">
	    <button type="button" class="close" data-dismiss="alert">&times;</button>
	    <h4>Warning!</h4>
	    Best check yo self, you're not...
    </div>

    <div class="alert alert-error">
	    <button type="button" class="close" data-dismiss="alert">&times;</button>
	    <h4>Warning!</h4>
	    Best check yo self, you're not...
    </div>

    <div class="alert alert-success">
	    <button type="button" class="close" data-dismiss="alert">&times;</button>
	    <h4>Warning!</h4>
	    Best check yo self, you're not...
    </div>

    <div class="alert alert-info">
	    <button type="button" class="close" data-dismiss="alert">&times;</button>
	    <h4>Warning!</h4>
	    Best check yo self, you're not...
    </div>

    <hr />

	<h2>Nivo Slider <small><a target="_blank" href="http://dev7studios.com/nivo-slider/#/documentation" title="Nivo Slider | Documentation">Documentation</a></small></h2>

	<div class="slider-wrapper theme-default">
		<div id="slider" class="nivoSlider">
			<a href="javascript: void(0)" title="Link Banner 1"> <img src="<?php bloginfo('template_url') ?>/assets/images/default/banner/banner1.jpg" alt="Banner 01"/> </a>
			<a href="javascript: void(0)" title="Link Banner 2"> <img src="<?php bloginfo('template_url') ?>/assets/images/default/banner/banner2.jpg" alt="Banner 02"/> </a>
		</div>
	</div>

	<hr />

	<h2>Validator jQuery Tools <small><a target="_blank" href="http://jquerytools.org/demos/validator/index.html" title="Validator jQuery Tools | Documentation">Documentation</a></small></h2>
	<form class="has-validation" name="form" action="" method="">
		
		<input type="color" name="favcolor">
		<input type="range" name="points" min="1" max="10">

		<progress value="75" max="100"></progress>

		<fieldset>
			<label>
				Name
				<input type="text" id="nome" name="nome" placeholder="Name" required="required"/>
			</label>

			<label>
				E-mail
				<input type="email" id="email" name="email" placeholder="E-mail" required="required"/>
			</label>
		</fieldset>

		<fieldset>
			<label>
				Select Options

				<select id="select" name="select" required="required">
					<option value="">-- Escolha uma das opções --</option>
					<option value="Opção 1">Opção 1</option>
					<option value="Opção 2">Opção 2</option>
					<option value="Opção 3">Opção 3</option>
					<option value="Opção 4">Opção 4</option>
					<option value="Opção 5">Opção 5</option>
				</select>
			</label>
		</fieldset>

		<fieldset>
			Sex

			<label ><input type="radio" name="sex" value="Male" /> Male</label>
			<label ><input type="radio" name="sex" value="Female" /> Female</label>
			

	ajdioasjido

			<label ><input type="radio" name="sexo" value="Male" /> Male</label>
			<label ><input type="radio" name="sexo" value="Female" /> Female</label>
			<label ><input type="radio" name="sexo" value="Female" /> gay</label>
		</fieldset>

		<fieldset>
			<h5>Likes</h5>
			<label for="game"><input id="game" type="checkbox" name="like" value="Game" /> Game</label>
			<label for="music"><input id="music" type="checkbox" name="like" value="Music" /> Music</label>
			<label for="travel"><input id="travel" type="checkbox" name="like" value="Travel" /> Travel</label>
			<label for="food"><input id="food" type="checkbox" name="like" value="Food" /> Food</label>
		</fieldset>

		<fieldset>
			<label>
				Message
				<textarea id="message" name="message" placeholder="Message" required="required"></textarea>
			</label>
		</fieldset>

		<input class="btn btn-submit" type="submit" value="Enviar">
	</form>

</section>