<section id="PagePortfolio" class="clearfix">
	
	 <?php
		$query 	= new WP_Query('post_type=portfolio&posts_per_page=99');
		while ( $query->have_posts() ){		
			$query->the_post();
			global $post;
			
			$dados =  get_post_meta($post->ID, WORDWEBPRESS_APP_NAME . '_metas_Caracteristicas');
			$dados = unserialize( base64_decode( $dados[0] ) );
	?>
                    
    <figure class="job" data-client="<?=$post->post_name?>" data-img="<?=wp_get_attachment_url( get_post_thumbnail_id($post->ID) );?>">
        <img src="<?=$dados['thumb']?>" alt="<?php bloginfo('name');?> | <?php the_title();?>" title="<?php bloginfo('name');?> | <?php the_title();?>"/>
        <figcaption id="hover"> <h2 class="JobTitle"> <?php the_title();?> </h2> </figcaption>
    </figure>
    
	<?php } ?>

</section>