<!-- 
Enjoy!
┈┈┈┈┈┈▕▔╲
┈┈┈┈┈┈┈▏▕
┈┈┈┈┈┈┈▏▕▂▂▂
▂▂▂▂▂▂╱┈▕▂▂▂▏
▉▉▉▉▉┈┈┈▕▂▂▂▏
▉▉▉▉▉┈┈┈▕▂▂▂▏
▔▔▔▔▔▔╲▂▕▂▂▏
-->
<!DOCTYPE html>
<html>
    
    <head>
        <meta charset="<?php bloginfo('charset'); ?>">
        
         <title><?php wp_title(); ?></title>
         
        <meta name="author" content="Agência Digital Interative Studio">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <?php /*Inserir google-site-verification*/?>

        <link href="<?php  bloginfo( 'template_url' ); ?>/assets/images/favicon.png" rel="shortcut icon" type="image/x-icon">
        <link href="<?php bloginfo( 'template_url' ); ?>/assets/images/favicon.png" rel="icon" type="image/x-icon">

        <link rel="stylesheet" type="text/css" href="<?php bloginfo('template_url');?>/assets/css/0.1_jquery.fancybox.css">
        <link rel="stylesheet" type="text/css" href="<?php bloginfo('template_url');?>/assets/css/style.css">
        <link href='http://fonts.googleapis.com/css?family=PT+Sans+Caption' rel='stylesheet' type='text/css'>
        <link href='http://fonts.googleapis.com/css?family=PT+Sans' rel='stylesheet' type='text/css'>
        <?php


            /*
             * wp_head();
              *
              *
              * <link rel="alternate" type="application/rss+xml" title="<?php bloginfo('name'); ?> RSS Feed" href="<?php bloginfo('rss2_url'); ?>">
                    <link rel="alternate" type="application/atom+xml" title="<?php bloginfo('name'); ?> Atom Feed" href="<?php bloginfo('atom_url'); ?>">
                    <link rel="pingback" href="<?php bloginfo('pingback_url'); ?>">
              *
              *
              * $this->helper('metas');
              * */
        ?>
    </head>

    <body <?php body_class(); ?>>

        <div id="RJRScroller" class="clearfix">
            <header class="clearfix">
                <a id="logo" href="<?php bloginfo('url');?>" title="<?php bloginfo('name');?>"> <?php bloginfo('url');?> </a>
                <nav>
                    <ul>
                        <li><a href="<?php bloginfo('url');?>" title="<?php bloginfo('name');?> | Página Inicial">Portfólio</a></li>
                        <li><a href="<?php bloginfo('url');?>/contato" title="<?php bloginfo('name');?> | Conato">Contato</a></li>
                    </ul>
                </nav>
                <button id="BtnMenuMobile" class="BtnMenuMobile"></button>
                <div id="HeaderInfos" class="NoMobile clearfix">
                    <ul id="ContactList">
                        <li><a class="HeaderIconFB" href="https://www.facebook.com/interativestudio" title="<?php bloginfo('name');?> | Facebook" target="_blank"></a></li>
                        <li><a class="HeaderIconTW" href="https://twitter.com/alanweb" title="<?php bloginfo('name');?> | Twitter" target="_blank"></a></li>
                        <li> 51 3463.3505 </li>
                    </ul>
                    <iframe src="//www.facebook.com/plugins/likebox.php?href=https%3A%2F%2Fwww.facebook.com%2Finterativestudio&amp;width=210&amp;height=258&amp;colorscheme=light&amp;show_faces=true&amp;header=false&amp;stream=false&amp;show_border=false&amp;appId=122998567854339" scrolling="no" frameborder="0" style="background: #ffffff; border:none; margin: 20px 0; overflow:hidden; width:210px; height:258px;" allowTransparency="true"></iframe>
                    <div class="txt-center">
                        <a class="EmailInfo" href="mailto: contato@interative.cc" title="<?php bloginfo('name');?> | Email">contato@interative.cc</a>
                        <p class="ass">© Interative Studio, 2010 - 2013.</p>
                        <a href="http://www.abcomm.com.br/" target="_blank" title="ABComm">
                            <img src="<?php bloginfo('template_url');?>/assets/images/ABComm.png" alt="<?php bloginfo('name');?> | Imagem ABCOMM" title="<?php bloginfo('name');?> | Imagem ABCOMM"/>
                        </a>
                    </div>
                </div>
            </header>
            <div id="RJRContent" class="clearfix">  <?=$this->content?> </div>

            <footer class="clearfix">
                <p class="txt-center">  © Interative Studio, 2010 - <?=date('Y')?>.</p>
            </footer>
        </div>

        <div id="loadding"></div>

        <script src="<?php bloginfo('template_url');?>/assets/javascripts/0.0_jquery-1.9.1.min.js"></script>
        <!--[if IE]>
            <script src="<?=bloginfo('template_url');?>/assets/javascripts/ie/1.0_css3.mediaqueries.js"></script>
        <![endif]-->

        <script src="http://cdnjs.cloudflare.com/ajax/libs/gsap/1.10.1/TweenMax.min.js" type="text/javascript"></script>
        <script src="<?php bloginfo('template_url');?>/assets/javascripts/2.0_modernizr.js"></script>
        <script src="<?php bloginfo('template_url');?>/assets/javascripts/2.3_jquery.mCustomScrollbar.concat.min.js"></script>
        <script src="<?php bloginfo('template_url');?>/assets/javascripts/2.5_jquery.fancybox.pack.js"></script>
        <script src="<?php bloginfo('template_url');?>/assets/javascripts/6.0_mask.js"></script>
        <script src="<?php bloginfo('template_url');?>/assets/javascripts/6.1_validator.jquery.tools.min.js"></script>
        <script src="<?php bloginfo('template_url');?>/assets/javascripts/8.0_is.functions.js"></script>
        <script src="<?php bloginfo('template_url');?>/assets/javascripts/9.0_is.common.js"></script>
    </body>
</html>