<html><head><title>Debug - 16/02/2012 às 13:12:50</title></head><body><table border="1" cellpadding="12"><tr><td align="center">Time for exec</td><td align="center">Mensage</td></tr><tr  style="background-color:#d6f0d6"><td>0.068113</td><td>Modules loaded successfully
</td></tr><tr  style="background-color:#d6f0d6"><td>0.068026</td><td>Setting a new value of variable system
</td></tr><tr  style="background-color:#d6f0d6"><td>0.052637</td><td>Generating rendering of the view: blank
</td></tr><tr  style="background-color:#d6f0d6"><td>0.052604</td><td>Content of the rendered view
</td></tr><tr  style="background-color:#d6f0d6"><td>0.052597</td><td>Adding to the project layout
</td></tr><tr  style="background-color:#d6f0d6"><td>0.05112</td><td>File: vendor/modernizr-1.7.min.js add on js container (non reduce)
</td></tr><tr  style="background-color:#d6f0d6"><td>0.051099</td><td>File: vendor/jquery.easing-1.3.pack.js add on js container (non reduce)
</td></tr><tr  style="background-color:#d6f0d6"><td>0.051082</td><td>File: vendor/jquery.mousewheel.min.js add on js container (non reduce)
</td></tr><tr  style="background-color:#d6f0d6"><td>0.051066</td><td>File: vendor/jquery.tinyscrollbar.min.js add on js container (non reduce)
</td></tr><tr  style="background-color:#d6f0d6"><td>0.05105</td><td>File: vendor/jquery.history.js add on js container
</td></tr><tr  style="background-color:#d6f0d6"><td>0.051034</td><td>File: 0_script.js add on js container
</td></tr><tr  style="background-color:#d6f0d6"><td>0.051019</td><td>File: 1_ajax.js add on js container
</td></tr><tr  style="background-color:#d6f0d6"><td>0.051004</td><td>File: 2_anima.js add on js container
</td></tr><tr  style="background-color:#d6f0d6"><td>0.050989</td><td>File: 3_loader.js add on js container
</td></tr><tr  style="background-color:#d6f0d6"><td>0.050959</td><td>File ( vendor/jquery.easing-1.3.pack ).js added successfully (non reduce)
</td></tr><tr  style="background-color:#d6f0d6"><td>0.050949</td><td>File ( vendor/jquery.mousewheel.min ).js added successfully (non reduce)
</td></tr><tr  style="background-color:#d6f0d6"><td>0.050938</td><td>File ( vendor/jquery.tinyscrollbar.min ).js added successfully (non reduce)
</td></tr><tr  style="background-color:#d6f0d6"><td>0.050927</td><td>File ( vendor/modernizr-1.7.min ).js added successfully (non reduce)
</td></tr><tr  style="background-color:#d6f0d6"><td>0.050914</td><td>File (  ).js generated successfully
</td></tr><tr  style="background-color:#d6f0d6"><td>0.050903</td><td>File (  ).js generated successfully
</td></tr><tr  style="background-color:#d6f0d6"><td>0.050892</td><td>File (  ).js generated successfully
</td></tr><tr  style="background-color:#d6f0d6"><td>0.050882</td><td>File (  ).js generated successfully
</td></tr><tr  style="background-color:#d6f0d6"><td>0.050872</td><td>File (  ).js generated successfully
</td></tr><tr  style="background-color:#d6f0d6"><td>0.050808</td><td>File: basic.css add on css container
</td></tr><tr  style="background-color:#d6f0d6"><td>0.050792</td><td>File: reset.css add on css container
</td></tr><tr  style="background-color:#d6f0d6"><td>0.050775</td><td>File: ie7-rack.css add on css container (rack)
</td></tr><tr  style="background-color:#d6f0d6"><td>0.050755</td><td>File: _functions.less add on css container
</td></tr><tr  style="background-color:#d6f0d6"><td>0.05074</td><td>File: basic.less add on css container
</td></tr><tr  style="background-color:#d6f0d6"><td>0.050725</td><td>Not rendering of css
</td></tr><tr  style="background-color:#d6f0d6"><td>0.050713</td><td>File ( basic ).css initalizing successfully
</td></tr><tr  style="background-color:#d6f0d6"><td>0.050701</td><td>File ( reset ).css initalizing successfully
</td></tr><tr  style="background-color:#d6f0d6"><td>0.050686</td><td>File ( ie7-rack ).css initializing successfully (rack)
</td></tr><tr  style="background-color:#d6f0d6"><td>0.050671</td><td>Starting the rendering of less
</td></tr><tr  style="background-color:#d6f0d6"><td>0.00021300000000002</td><td>File ( _functions,basic ).less reloaded successfully
</td></tr><tr  style="background-color:#d6f0d6"><td>0.00014900000000001</td><td>Image: bg.jpg added successfully
</td></tr><tr  style="background-color:#d6f0d6"><td>0.00012699999999999</td><td>Image: facebook.png added successfully
</td></tr><tr  style="background-color:#d6f0d6"><td>0.000108</td><td>Image: twitter.png added successfully
</td></tr><tr  style="background-color:#d6f0d6"><td>8.9000000000006E-5</td><td>Image: loader-content.png added successfully
</td></tr><tr  style="background-color:#d6f0d6"><td>2.000000000002E-5</td><td>File menu successfully started, helpers path
</td></tr><tr  style="background-color:#d6f0d6"><td>1.2000000000012E-5</td><td>Layout successfully mastered
</td></tr></table></body></html>